### ISSUE TITLE
Error wrt. the paper

### ISSUE THREAD

**Issue by rjanvier** [syncle/photo-consistency#1]
Hello,
Thank you very much for for making this code available.
I noticed an error on this line : https://github.com/syncle/photo-consistency/blob/master/fn_estimation.m#L7. 

On this line, you are evaluating dimensions of the 3*1 cell, and not dimensions of the m*n Obs matrix so lambda will always equals to 1. in the paper lamdba is initalized more like the following lambda = 1/sqrt(min(size(O{1},1),size(O{1},2)));

**Comment by syncle** [comment]
Thanks for the comment! I fixed the bug.
